version: '3'

services:
#  frontend:
#    image: nginx:alpine
#    container_name: frontend
#    volumes:
#      - ./frontend:/usr/share/nginx/html
#    ports:
#      - "3000:80"
#    networks:
#      - demo-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment: # db가 의존성에 포함되어 있어서 임시로 제작. .env 파일로 변경 예정
      - DB_URL=jdbc:h2:mem:testdb
      - DB_USERNAME=sa
      - DB_PASSWORD=password
    networks:
      - demo-network

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    networks:
      - demo-network
    depends_on:
      #- frontend
      - backend

networks:
  demo-network:
    driver: bridge